services:
  postgres:
    image: postgres:15
    cpus: 1
    mem_reservation: 128m
    mem_limit: 512m
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_MULTIPLE_DATABASES: "iam:iam:iam,moj:moj:moj"
    volumes:
      - "./scripts:/docker-entrypoint-initdb.d"
    networks:
      - moj

  auth:
    image: quay.io/keycloak/keycloak:21.1
    cpus: 1
    mem_reservation: 512m
    mem_limit: 1g
    restart: unless-stopped
    ports:
      - "8888:8080"
    command:
      - "start-dev"
      - "--import-realm"
      - "--hostname=host.docker.internal"
      - "--hostname-strict-https=false"
      - "--http-enabled=true"
    environment:
      KEYCLOAK_ADMIN: "keycloak"
      KEYCLOAK_ADMIN_PASSWORD: "keycloak"
      KC_DB: postgres
      KC_DB_USERNAME: iam
      KC_DB_PASSWORD: iam
      KC_DB_URL: "jdbc:postgresql://postgres:5432/iam"
    volumes:
      - "./realms:/opt/keycloak/data/import"
    networks:
      - moj
    depends_on:
      postgres:
        condition: service_started

  controller:
    image: your.registry/moj/moj-controller:17
    cpus: 2
    mem_reservation: 1g
    mem_limit: 2g
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "61616:61616"
    environment:
      OIDC_ISSUER_URI: "http://host.docker.internal:8888/realms/moj"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/moj"
      SPRING_DATASOURCE_USERNAME: "moj"
      SPRING_DATASOURCE_PASSWORD: "moj"
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"
    networks:
      - moj
    depends_on:
      postgres:
        condition: service_started
      auth:
        condition: service_started

  worker:
    image: your.registry/moj/moj-worker:17
    cpus: 3
    mem_reservation: 1g
    mem_limit: 2g
    restart: unless-stopped
    environment:
      CONTROLLER_URI: "http://controller:8080"
      CONTROLLER_BROKER_URI: "tcp://controller:61616"
      SPRING_JMS_LISTENER_CONCURRENCY: 3
      SPRING_JMS_LISTENER_MAX_CONCURRENCY: 3
    networks:
      - moj
    depends_on:
      controller:
        condition: service_started

networks:
  moj: {}